version: '3'

networks:
  services:
    ipam:
      config:
        - subnet: 173.17.0.0/24

services:
  #
  # Webserver
  #
  webserver:
    image: indy-node
    build:
      context: .
      dockerfile: pool.dockerfile
    command: 'bash -c ''./scripts/start_webserver.sh'''
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - HOST=173.17.0.100
      - RUST_LOG=${RUST_LOG}
    networks:
      services:
        ipv4_address: 173.17.0.100
    ports:
      - 9000:8000
    depends_on:
      - node1
      - node2
      - node3
      - node4
    volumes:
      - ./server:/home/indy/server
      - webserver-cli:/home/indy/.indy-cli
      - node1-data:/home/indy/.mnt/node1
      - node2-data:/home/indy/.mnt/node2
      - node3-data:/home/indy/.mnt/node3
      - node4-data:/home/indy/.mnt/node4

  #
  # Nodes
  #
  node1:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 1'''
    networks:
      services:
        ipv4_address: 173.17.0.101
    ports:
      - 9701:9701
      - 9702:9702
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
#      - HOST=173.17.0.101
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node1-data:/home/indy/ledger

  node2:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 2'''
    networks:
      services:
        ipv4_address: 173.17.0.102
    ports:
      - 9703:9703
      - 9704:9704
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - RUST_LOG=${RUST_LOG}
#      - HOST=173.17.0.102
    volumes:
      - node2-data:/home/indy/ledger

  node3:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 3'''
    networks:
      services:
        ipv4_address: 173.17.0.103
    ports:
      - 9705:9705
      - 9706:9706
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
#      - HOST=173.17.0.103
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node3-data:/home/indy/ledger

  node4:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 4'''
    networks:
      services:
        ipv4_address: 173.17.0.104
    ports:
      - 9707:9707
      - 9708:9708
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
#      - HOST=173.17.0.104
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node4-data:/home/indy/ledger

  #
  # Agents
  #
  denis:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://cdn3.iconfinder.com/data/icons/human-resources-management/512/business_man_office_male-512.png
      - THEME=DarkGray
      - PORT=3000
      - NAME=Denis
      - EMAIL=dstefanescu@uoc.edu
      - PASSWORD=123
      - USERNAME=denis
      - PUBLIC_DID_ENDPOINT=173.17.0.150:3000
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3000:3000
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.150
    volumes:
      - node1-data:/home/indy/ledger

  osakidetza:
    image: indy-agentjs
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ2G1IgQuVYUualq7PBzLo5A61glMzwc2R1w_x5uJspPBTXQ-id
      - THEME=OliveDrab
      - PORT=3002
      - NAME=Osakidetza
      - EMAIL=osakidetza@eus.es
      - PASSWORD=123
      - USERNAME=osakidetza
      - PUBLIC_DID_ENDPOINT=173.17.0.170:3002
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3002:3002
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - denis
    networks:
      services:
        ipv4_address: 173.17.0.170
    volumes:
      - node1-data:/home/indy/ledger

  AP-HP:
    image: indy-agentjs
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://cdn.iconscout.com/icon/free/png-512/ford-14-569590.png
      - THEME=LightSteelBlue
      - PORT=3003
      - NAME=AP-HÃ´pitaux de Paris
      - EMAIL=AP-HP@gob.fr
      - PASSWORD=123
      - USERNAME=aphp
      - PUBLIC_DID_ENDPOINT=173.17.0.180:3003
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3003:3003
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - denis
    networks:
      services:
        ipv4_address: 173.17.0.180
    volumes:
      - node1-data:/home/indy/ledger

volumes:
  webserver-cli:
  node1-data:
  node2-data:
  node3-data:
  node4-data:
